language: python
python:
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO=1.4.3
  - DJANGO=1.5.1
  - DJANGO=1.6

install:
  - pip install -q Django==$DJANGO --use-mirrors

script: python setup.py test

matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.4.3
    - python: 3.3
      env: DJANGO=1.4.3

notifications:
  email:
    recipients:
      - bjasper@gmail.com
